# See https://docs.minecraftforge.net/en/1.21.x/gettingstarted/modfiles/#modstoml
modLoader="javafml"
loaderVersion="${forge_loader_version_range}"
license="${license}"

[[mods]]
modId="${example_mod_id}"
version="${version}"
displayName="${example_mod_name}"
authors="${mod_author}"
description="Tiny QoL example built on Mycel."

[[dependencies.${example_mod_id}]]
modId="forge"
mandatory=true
versionRange="${forge_loader_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${example_mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${example_mod_id}]]
modId="${mod_id}"
mandatory=true
versionRange="[${version},)"
ordering="AFTER"
side="BOTH"
