modLoader="javafml"
loaderVersion="${neoforge_loader_version_range}"
license="${license}"

[[mods]]
modId="${example_mod_id}"
version="${version}"
displayName="${example_mod_name}"
authors="${mod_author}"
description="Tiny QoL example built on Mycel."

[[dependencies.${example_mod_id}]]
modId="neoforge"
type="required"
versionRange="${neoforge_loader_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${example_mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${example_mod_id}]]
modId="${mod_id}"
type="required"
versionRange="[${version},)"
ordering="AFTER"
side="BOTH"
